# Generated by Django 3.2 on 2022-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.TimeField()),
                ('last_value', models.FloatField()),
                ('change', models.FloatField()),
                ('percentage', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IndexInfluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('final_price', models.FloatField()),
                ('influence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('yesterday_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('count', models.BigIntegerField()),
                ('volume', models.FloatField()),
                ('value', models.FloatField()),
                ('final_deal', models.FloatField()),
            ],
        ),
    ]
